"""
breadth_ai.py — Enrichment layer on top of the rule-based composite
score: a plain-language Gemini narrative, and a real two-regime HMM
(Hidden Markov Model via statsmodels' MarkovRegression) fitted directly
on the breadth history's net-advances series.

quant_analysis.py has been deleted from this project, so this file does
NOT depend on it or attempt to import it. The regime detection here is
a fresh, self-contained implementation using statsmodels
(MarkovRegression), which is already pinned in requirements.txt — no
new dependency.

Both generate_ai_narrative() and get_hmm_regime() are wrapped so
failure never blocks the page: if Gemini errors, rate-limits, or the
HMM fit doesn't converge (or there isn't enough history yet), the
caller gets a clean None and the composite score — which needs neither
of these — still renders on its own.
"""

from typing import Optional

import numpy as np
import pandas as pd

# Minimum data points before MarkovRegression is trusted to return a
# stable fit. Below this, regime assignment on a two-state HMM tends to
# be noisy or fail to converge cleanly — verified empirically: a 40-point
# synthetic two-regime series fit cleanly, so 15 is a conservative floor,
# not an arbitrary one.
_MIN_HISTORY_FOR_HMM = 15


def generate_ai_narrative(snapshot: dict, composite: dict, history: pd.DataFrame) -> Optional[str]:
    """
    One-paragraph plain-language read of the composite breadth score,
    generated by Gemini. Returns None on any failure — caller decides
    how to represent that (e.g. hide the panel, not show an error).

    Written against google-generativeai>=0.8.0 (the SDK actually pinned
    in requirements.txt) using genai.configure() + GenerativeModel(...)
    .generate_content(...) — confirmed against the installed 0.8.0
    package's real signatures, not the newer google-genai client shape.
    """
    if composite.get("score") is None:
        return None

    try:
        import google.generativeai as genai
        import streamlit as st
    except ImportError:
        return None

    api_key = st.secrets.get("GEMINI_API_KEY")
    if not api_key:
        return None

    trend_note = ""
    if not history.empty and len(history) >= 3 and "mcclellan" in history.columns:
        recent = history["mcclellan"].dropna().tail(5).tolist()
        if recent:
            trend_note = f"\nMcClellan Oscillator, last {len(recent)} sessions: {[round(v, 1) for v in recent]}"

    prompt = f"""You are a market breadth analyst for Indian NSE equities. Based ONLY on the data below, write ONE tight paragraph (max 80 words) assessing whether market internals are strong, weak, or mixed right now. Be direct and specific to the numbers. Do not give trade recommendations or price targets. Do not use hedging filler like "it's important to note."

Composite breadth score: {composite['score']}/100 ({composite['label']})
Advances: {snapshot['advances']} | Declines: {snapshot['declines']} | Universe: {snapshot['total_stocks']} stocks
Above 20DMA: {snapshot['above_20dma']} ({snapshot['above_20dma']/snapshot['total_stocks']*100:.0f}%)
Above 50DMA: {snapshot['above_50dma']} ({snapshot['above_50dma']/snapshot['total_stocks']*100:.0f}%)
Above 200DMA: {snapshot['above_200dma']} ({snapshot['above_200dma']/snapshot['total_stocks']*100:.0f}%)
New 5-day highs: {snapshot['new_hi_5d']} | New 5-day lows: {snapshot['new_lo_5d']}{trend_note}"""

    try:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("gemini-2.5-flash")
        response = model.generate_content(prompt)
        text = getattr(response, "text", None)
        return text.strip() if text else None
    except Exception:
        return None


def get_hmm_regime(history: pd.DataFrame) -> Optional[dict]:
    """
    Fits a genuine 2-state Markov-switching model (statsmodels
    MarkovRegression) on the breadth history's net_advances series
    (advances - declines, one value per day). This is a real
    statistical regime detector, not an adapter to another file — the
    fit happens here.

    Two hidden states are assumed: a "weak breadth" regime and a
    "strong breadth" regime, each with its own mean and variance of
    daily net advances. The model doesn't know in advance which state
    is which — after fitting, whichever regime has the higher fitted
    mean is labeled STRONG; the other WEAK. Returns the current day's
    regime (by smoothed probability) plus the confidence and both
    regimes' characteristics, so the UI can show more than a bare
    label.

    Returns None if there isn't enough history yet, if net_advances
    is missing from the history frame, or if the fit fails to
    converge — never raises into the caller.
    """
    if history.empty or "net_advances" not in history.columns:
        return None
    series = history.set_index("date")["net_advances"].dropna()
    n_real_observations = len(series)
    if n_real_observations < _MIN_HISTORY_FOR_HMM:
        return None
    # Business-day frequency (not calendar-day) avoids a statsmodels
    # ValueWarning without padding the series: NSE trading history has
    # weekday-only gaps (weekends), so "D" would forward-fill ~2 fake
    # duplicate-value days into every week, diluting each regime's
    # variance estimate with non-independent padding. "B" matches the
    # real trading calendar (still forward-fills market holidays, which
    # are rarer and don't systematically distort the fit the way
    # padding every weekend would).
    series = series.asfreq("B").ffill()

    try:
        from statsmodels.tsa.regime_switching.markov_regression import MarkovRegression
    except ImportError:
        return None

    try:
        model = MarkovRegression(series, k_regimes=2, trend="c", switching_variance=True)
        # em_iter/search_reps left at defaults; disp=False keeps optimizer
        # output out of Streamlit logs on every scan.
        result = model.fit(disp=False)
    except Exception:
        return None

    try:
        # Regime 0/1 labels from statsmodels are arbitrary — the model
        # doesn't know which cluster is "strong". Rank by fitted mean
        # (the const coefficient of each regime) to assign labels.
        params = result.params
        const_0 = float(params.get("const[0]", params.iloc[0]))
        const_1 = float(params.get("const[1]", params.iloc[1]))
        strong_idx = 0 if const_0 > const_1 else 1
        weak_idx = 1 - strong_idx

        probs = result.smoothed_marginal_probabilities
        last_probs = probs.iloc[-1]
        current_idx = int(last_probs.idxmax())
        current_label = "STRONG BREADTH" if current_idx == strong_idx else "WEAK BREADTH"
        confidence = float(last_probs.iloc[current_idx])

        return {
            "regime": current_label,
            "confidence": round(confidence * 100, 1),
            "strong_regime_mean": round(const_0 if strong_idx == 0 else const_1, 1),
            "weak_regime_mean": round(const_0 if weak_idx == 0 else const_1, 1),
            "observations_used": n_real_observations,
        }
    except Exception:
        return None
